import type { Metadata } from "next";
import { Inter } from 'next/font/google'
import './globals.css'
import { AuthContextProvider } from "./auth/context/contextProvider";
import { DatabaseContextProvider } from "./context/databaseContext";
import { Header } from "./components/header/headerView";
import { Footer } from "./components/footer/footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthContextProvider>
      <DatabaseContextProvider>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </DatabaseContextProvider>
    </AuthContextProvider>
  );
}
